// Code generated by cmd/cgo; DO NOT EDIT.

//line /Users/zhangyanfei/work_my/go-training/6-cgo/examples/e07/main.go:1:1
package main

//int sum(int a, int b) { return a+b; }
import _ "unsafe"

func main() {
	println(( /*line :7:10*/_Cfunc_sum /*line :7:14*/)(1, 1))
}
